version: '3.0'

services:
  website:
    build: ./
    image: daru-website:latest
    container_name: daru-website
    networks:
      - nginx-proxy-manager_default
    ports:
      - 88:80
    restart: unless-stopped
    volumes:
      - ./src:/usr/share/nginx/html
      - ./nginx:/etc/nginx/conf.d/

networks:
  nginx-proxy-manager_default:
    external: true